const CFG=window.ML_CONFIG||{};const db=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_KEY);
const $=id=>document.getElementById(id), money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const norm=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const state={orders:[],products:[],cats:[],clients:[],filter:"todos",options:[],promos:[],page:"dashboard",sound:true};
const statusOf=o=>{const m=[...String(o||"").matchAll(/\[ML_STATUS\](novo|preparo|entrega|entregue|cancelado)\[\/ML_STATUS\]/g)];return m.length?m.at(-1)[1]:"novo"};
const itemsOf=o=>{const m=String(o||"").match(/\[ML_ITENS\]([\s\S]*?)\[\/ML_ITENS\]/);if(!m)return[];try{return JSON.parse(decodeURIComponent(m[1]))}catch{return[]}};
const setStatus=(o,s)=>String(o||"").replace(/\n?\[ML_STATUS\][\s\S]*?\[\/ML_STATUS\]/g,"").trim()+`\n[ML_STATUS]${s}[/ML_STATUS]`;
const label=s=>({novo:"Novo",preparo:"Em preparo",entrega:"Saiu para entrega",entregue:"Entregue",cancelado:"Cancelado"}[s]||s);
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2300)}
async function cfgGet(key,fallback={}){const r=await db.from("configuracoes").select("valor").eq("chave",key).maybeSingle();if(r.error||!r.data)return fallback;try{return JSON.parse(r.data.valor||"null")??fallback}catch{return fallback}}
async function cfgSave(key,val){const r=await db.from("configuracoes").upsert({chave:key,valor:JSON.stringify(val),updated_at:new Date().toISOString()},{onConflict:"chave"});if(r.error)throw r.error}
async function load(){
  const [o,p,c,cl]=await Promise.all([
    db.from("pedidos").select("*").order("created_at",{ascending:false}).limit(500),
    db.from("produtos").select("*,categorias(nome,emoji)").order("ordem"),
    db.from("categorias").select("*").order("ordem"),
    db.from("clientes").select("*").order("nome")
  ]);
  state.orders=o.data||[];state.products=p.data||[];state.cats=c.data||[];state.clients=cl.data||[];
  $("connection").textContent=(o.error||p.error||c.error)?"Conectado com avisos":"Conectado";
  renderAll();
}
function renderAll(){renderDashboard();renderOrders();renderProducts();renderCats();renderClients();renderReports();renderOptions();renderPromos();loadSettings()}
function renderDashboard(){
  const today=new Date().toISOString().slice(0,10),todayOrders=state.orders.filter(o=>(o.created_at||"").slice(0,10)===today&&statusOf(o.observacoes)!=="cancelado"),sales=todayOrders.reduce((a,o)=>a+Number(o.total||0),0);
  $("kpis").innerHTML=[
    ["Pedidos hoje",todayOrders.length],["Faturamento hoje",money(sales)],["Em preparo",state.orders.filter(o=>statusOf(o.observacoes)==="preparo").length],["Novos pedidos",state.orders.filter(o=>statusOf(o.observacoes)==="novo").length]
  ].map(x=>`<div class="kpi"><small>${x[0]}</small><b>${x[1]}</b></div>`).join("");
  const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const key=d.toISOString().slice(0,10);return {key,label:d.toLocaleDateString("pt-BR",{weekday:"short"}).replace(".",""),value:state.orders.filter(o=>(o.created_at||"").slice(0,10)===key&&statusOf(o.observacoes)!=="cancelado").reduce((a,o)=>a+Number(o.total||0),0)}}),max=Math.max(...days.map(x=>x.value),1);
  $("salesChart").innerHTML=days.map(x=>`<div class="bar" style="height:${Math.max(5,x.value/max*175)}px"><b>${money(x.value).replace(",00","")}</b><span>${x.label}</span></div>`).join("");
  const sts=["novo","preparo","entrega","entregue","cancelado"],total=Math.max(state.orders.length,1);$("statusChart").innerHTML=sts.map((s,i)=>`<div class="status-row"><span>${label(s)}</span><div class="status-track"><div class="status-fill ${s==="cancelado"?"red":s==="entregue"?"green":s==="novo"?"red":""}" style="width:${state.orders.filter(o=>statusOf(o.observacoes)===s).length/total*100}%"></div></div><b>${state.orders.filter(o=>statusOf(o.observacoes)===s).length}</b></div>`).join("");
  $("recentOrders").innerHTML=state.orders.slice(0,8).map(o=>`<div class="list-row"><span><b>#${String(o.id).slice(-5)}</b> · ${esc(o.Cliente||"Cliente")}<small>${new Date(o.created_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</small></span><strong>${money(o.total)}</strong></div>`).join("")||`<p class="muted">Nenhum pedido.</p>`;
  const counts={};state.orders.flatMap(o=>itemsOf(o.observacoes)).forEach(i=>{counts[i.nome]=(counts[i.nome]||0)+Number(i.quantidade||1)});$("topProducts").innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,6).map((x,i)=>`<div class="list-row"><span><b>${i+1}.</b> ${esc(x[0])}</span><strong>${x[1]}</strong></div>`).join("")||`<p class="muted">Ainda sem vendas.</p>`;
  $("newBadge").textContent=state.orders.filter(o=>statusOf(o.observacoes)==="novo").length;
}
function renderOrders(){
  const c={todos:state.orders.length,novo:0,preparo:0,entrega:0,entregue:0,cancelado:0};state.orders.forEach(o=>c[statusOf(o.observacoes)]++);
  Object.entries(c).forEach(([k,v])=>{const el=$("count"+k[0].toUpperCase()+k.slice(1));if(el)el.textContent=v});
  const list=state.filter==="todos"?state.orders:state.orders.filter(o=>statusOf(o.observacoes)===state.filter);
  $("orders").innerHTML=list.map(o=>{const s=statusOf(o.observacoes),its=itemsOf(o.observacoes),obs=String(o.observacoes||"").replace(/\[ML_[A-Z_]+\][\s\S]*?\[\/ML_[A-Z_]+\]/g,"").trim();return `<article class="order-card ${s==="novo"?"new":""}">
    <div class="order-head"><div><h3>Pedido #${String(o.id).slice(-5)}</h3><span class="muted">${esc(o.Cliente||"Cliente")} · ${new Date(o.created_at).toLocaleString("pt-BR")}</span></div><span class="status-pill s-${s}">${label(s)}</span></div>
    <div class="order-items">${its.map(i=>`<div><b>${Number(i.quantidade||1)}x</b> ${esc(i.nome)} <span class="muted">— ${money(Number(i.preco||0)*Number(i.quantidade||1))}</span>${i.adicionais?.length?`<br><span class="muted">+ ${i.adicionais.map(a=>esc(a.nome)).join(", ")}</span>`:""}${i.obs?`<br><span class="muted">Obs: ${esc(i.obs)}</span>`:""}</div>`).join("")||"Itens não detalhados"}<br><span class="muted">${esc(o.endereco||"Retirada")} ${o.referencia?` · ${esc(o.referencia)}`:""}</span>${obs?`<br><span class="muted">Obs: ${esc(obs)}</span>`:""}</div>
    <div class="order-bottom"><b class="order-total">${money(o.total)}</b><div class="order-actions"><button class="ghost" data-print="${o.id}">Imprimir</button><select data-status="${o.id}">${["novo","preparo","entrega","entregue","cancelado"].map(x=>`<option value="${x}" ${x===s?"selected":""}>${label(x)}</option>`).join("")}</select></div></div>
  </article>`}).join("")||`<div class="panel"><p class="muted">Nenhum pedido neste filtro.</p></div>`;
  document.querySelectorAll("[data-status]").forEach(x=>x.onchange=()=>changeStatus(x.dataset.status,x.value));
  document.querySelectorAll("[data-print]").forEach(x=>x.onclick=()=>printOrder(state.orders.find(o=>String(o.id)===String(x.dataset.print))));
}
async function changeStatus(id,s){const o=state.orders.find(x=>String(x.id)===String(id));if(!o)return;const r=await db.from("pedidos").update({observacoes:setStatus(o.observacoes,s)}).eq("id",o.id);if(r.error)return toast(r.error.message);o.observacoes=setStatus(o.observacoes,s);renderAll();toast("Status atualizado")}
function printOrder(o){if(!o)return;const its=itemsOf(o.observacoes),obs=String(o.observacoes||"").replace(/\[ML_[A-Z_]+\][\s\S]*?\[\/ML_[A-Z_]+\]/g,"").trim();const w=open("","_blank","width=420,height=700");if(!w)return toast("Permita pop-ups para imprimir");w.document.write(`<html><head><meta charset=utf-8><title>Pedido</title><style>@page{size:58mm auto;margin:0}body{width:58mm;margin:0;padding:3mm;font:12px Arial;color:#000}.c{text-align:center}.line{border-top:1px dashed #000;margin:7px 0}.row{padding:5px 0;border-bottom:1px dotted #777}.tot{display:flex;justify-content:space-between;font-weight:900;font-size:15px}</style></head><body><div class=c><b style="font-size:17px">MIGUEL LANCHES</b><br>PEDIDO #${String(o.id).slice(-5)}<br>${new Date(o.created_at).toLocaleString("pt-BR")}</div><div class=line></div><b>CLIENTE:</b> ${esc(o.Cliente)}<br><b>TELEFONE:</b> ${esc(o.telefone||"")}<br><b>END:</b> ${esc(o.endereco||"Retirada")}<br><b>REF:</b> ${esc(o.referencia||"—")}<div class=line></div>${its.map(i=>`<div class=row><b>${i.quantidade}x</b> ${esc(i.nome)}<br>${money(Number(i.preco||0)*Number(i.quantidade||1))}${i.adicionais?.length?`<br><small>+ ${i.adicionais.map(a=>esc(a.nome)).join(", ")}</small>`:""}${i.obs?`<br><small>Obs: ${esc(i.obs)}</small>`:""}</div>`).join("")}<div class=line></div><b>OBS:</b> ${esc(obs||"—")}<div class=line></div><div class=tot><span>TOTAL</span><span>${money(o.total)}</span></div><div class=line></div><div class=c>Obrigado!</div><script>window.print()</script></body></html>`);w.document.close()}
function renderProducts(){
  const q=norm($("productSearch")?.value),cat=$("productCat")?.value||"";if($("productCat")&&$("productCat").options.length!==state.cats.length+1)$("productCat").innerHTML='<option value="">Todas as categorias</option>'+state.cats.map(c=>`<option value="${c.id}">${esc(c.nome)}</option>`).join("");
  const rows=state.products.filter(p=>(!q||norm(p.nome).includes(q))&&(!cat||String(p.categoria_id)===String(cat)));
  $("productsTable").innerHTML=rows.map(p=>`<tr><td><div class="product-cell">${p.imagem_url?`<img class="product-img" src="${esc(p.imagem_url)}">`:`<span class="product-img"></span>`}<span><b>${esc(p.nome)}</b><small class="muted">${esc(p.descricao||"")}</small></span></div></td><td>${esc(p.categorias?.nome||"—")}</td><td><b>${money(p.preco)}</b></td><td><button class="toggle ${p.destaque?"on":""}" data-feature="${p.id}" title="Destaque"></button></td><td><button class="toggle ${p.ativo!==false?"on":""}" data-active="${p.id}"></button></td><td><button class="ghost" data-edit="${p.id}">Editar</button></td></tr>`).join("")||`<tr><td colspan="6" class="muted">Nenhum produto.</td></tr>`;
  document.querySelectorAll("[data-feature]").forEach(b=>b.onclick=()=>toggleProduct(b.dataset.feature,"destaque",!b.classList.contains("on")));
  document.querySelectorAll("[data-active]").forEach(b=>b.onclick=()=>toggleProduct(b.dataset.active,"ativo",!b.classList.contains("on")));
  document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>productForm(state.products.find(p=>String(p.id)===String(b.dataset.edit))));
}
async function toggleProduct(id,field,value){const r=await db.from("produtos").update({[field]:value}).eq("id",id);if(r.error)return toast(r.error.message);const p=state.products.find(x=>String(x.id)===String(id));if(p)p[field]=value;renderProducts();toast(value?"Ativado":"Desativado")}
function productForm(p={}){
  $("modalBody").innerHTML=`<h2>${p.id?"Editar produto":"Novo produto"}</h2><div class="form-grid">
  <label class="field">Nome<input id="fName" value="${esc(p.nome||"")}"></label>
  <label class="field">Categoria<select id="fCat">${state.cats.map(c=>`<option value="${c.id}" ${String(c.id)===String(p.categoria_id)?"selected":""}>${esc(c.nome)}</option>`).join("")}</select></label>
  <label class="field">Preço<input id="fPrice" type="number" step="0.01" value="${Number(p.preco||0)}"></label>
  <label class="field">Imagem URL<input id="fImage" value="${esc(p.imagem_url||"")}" placeholder="https://..."></label>
  <label class="field" style="grid-column:1/-1">Descrição<textarea id="fDesc" rows="3">${esc(p.descricao||"")}</textarea></label>
  </div><button class="primary" id="saveProduct">Salvar produto</button>`;
  $("modal").classList.remove("hidden");$("saveProduct").onclick=async()=>{const data={nome:$("fName").value.trim(),categoria_id:$("fCat").value,preco:Number($("fPrice").value||0),imagem_url:$("fImage").value.trim()||null,descricao:$("fDesc").value.trim(),ativo:p.ativo!==false};if(!data.nome||data.preco<0)return toast("Preencha nome e preço.");const r=p.id?await db.from("produtos").update(data).eq("id",p.id):await db.from("produtos").insert(data);if(r.error)return toast(r.error.message);closeModal();await load();toast("Produto salvo")}}
function renderCats(){$("categoryGrid").innerHTML=state.cats.map(c=>`<div class="category-card">${c.imagem_url?`<img class="cat-img" src="${esc(c.imagem_url)}">`:`<div class="cat-img"></div>`}<div><h3>${esc(c.nome)}</h3><p>${c.ativo===false?"Inativa":"Ativa"} · ordem ${c.ordem||0}</p></div><div class="cat-actions"><button class="ghost" data-cat-edit="${c.id}">Editar</button></div></div>`).join("")||`<div class="panel">Nenhuma categoria.</div>`;document.querySelectorAll("[data-cat-edit]").forEach(b=>b.onclick=()=>categoryForm(state.cats.find(c=>String(c.id)===String(b.dataset.catEdit))))}
function categoryForm(c={}){
  $("modalBody").innerHTML=`<h2>${c.id?"Editar categoria":"Nova categoria"}</h2><label class="field">Nome<input id="cName" value="${esc(c.nome||"")}"></label><label class="field">Imagem URL<input id="cImage" value="${esc(c.imagem_url||"")}"></label><label class="field">Ordem<input id="cOrder" type="number" value="${Number(c.ordem||99)}"></label><label class="field check"><input id="cActive" type="checkbox" ${c.ativo!==false?"checked":""}> Ativa</label><button class="primary" id="saveCat">Salvar categoria</button>`;
  $("modal").classList.remove("hidden");$("saveCat").onclick=async()=>{const data={nome:$("cName").value.trim(),imagem_url:$("cImage").value.trim()||null,ordem:Number($("cOrder").value||99),ativo:$("cActive").checked};if(!data.nome)return toast("Informe o nome.");const r=c.id?await db.from("categorias").update(data).eq("id",c.id):await db.from("categorias").insert(data);if(r.error)return toast(r.error.message);closeModal();await load();toast("Categoria salva")}}
async function renderOptions(){state.options=await cfgGet("opcoes_catalogo",[]);$("optionsList").innerHTML=state.options.map((x,i)=>`<div class="option-row"><b>${esc(x.nome)}</b><span>${esc(x.categoria||"Geral")}</span><span>${money(x.preco||0)}</span><button class="danger-btn" data-del-opt="${i}">Excluir</button></div>`).join("")||`<p class="muted">Nenhuma opção cadastrada.</p>`;document.querySelectorAll("[data-del-opt]").forEach(b=>b.onclick=async()=>{state.options.splice(Number(b.dataset.delOpt),1);await cfgSave("opcoes_catalogo",state.options);renderOptions();toast("Opção removida")})}
function optionForm(){ $("modalBody").innerHTML=`<h2>Nova opção</h2><label class="field">Nome<input id="oName" placeholder="Ex.: Bacon"></label><label class="field">Categoria<input id="oCat" placeholder="Ex.: Lanches"></label><label class="field">Preço adicional<input id="oPrice" type="number" step="0.01" value="0"></label><button class="primary" id="saveOpt">Salvar</button>`;$("modal").classList.remove("hidden");$("saveOpt").onclick=async()=>{const x={nome:$("oName").value.trim(),categoria:$("oCat").value.trim(),preco:Number($("oPrice").value||0)};if(!x.nome)return toast("Informe o nome.");state.options.push(x);await cfgSave("opcoes_catalogo",state.options);closeModal();renderOptions();toast("Opção salva")}}
async function renderPromos(){state.promos=await cfgGet("promocoes",[]);$("promoList").innerHTML=state.promos.map((x,i)=>`<div class="promo-row"><b>${esc(x.nome)}</b><span>${Number(x.desconto||0)}% de desconto</span><span>${x.ativa?"Ativa":"Inativa"}</span><button class="${x.ativa?"ghost":"primary"}" data-promo="${i}">${x.ativa?"Desativar":"Ativar"}</button></div>`).join("")||`<p class="muted">Nenhuma promoção.</p>`;document.querySelectorAll("[data-promo]").forEach(b=>b.onclick=async()=>{state.promos[Number(b.dataset.promo)].ativa=!state.promos[Number(b.dataset.promo)].ativa;await cfgSave("promocoes",state.promos);renderPromos()})}
function promoForm(){$("modalBody").innerHTML=`<h2>Nova promoção</h2><label class="field">Nome<input id="prName" placeholder="Ex.: Combo da semana"></label><label class="field">Desconto %<input id="prDiscount" type="number" min="0" max="100" value="10"></label><button class="primary" id="savePromo">Salvar</button>`;$("modal").classList.remove("hidden");$("savePromo").onclick=async()=>{const x={nome:$("prName").value.trim(),desconto:Number($("prDiscount").value||0),ativa:true,criadaEm:new Date().toISOString()};if(!x.nome)return toast("Informe o nome.");state.promos.push(x);await cfgSave("promocoes",state.promos);closeModal();renderPromos();toast("Promoção criada")}}
function renderClients(){const q=norm($("clientSearch")?.value);const rows=state.clients.filter(c=>!q||norm(c.nome).includes(q)||String(c.telefone||"").includes(q)).map(c=>{const orders=state.orders.filter(o=>String(o.telefone||"")===String(c.telefone||""));return {...c,n:orders.length,total:orders.reduce((a,o)=>a+Number(o.total||0),0)}});$("clientsTable").innerHTML=rows.map(c=>`<tr><td><b>${esc(c.nome)}</b></td><td>${esc(c.telefone||"")}</td><td>${esc(c.endereco||"")}</td><td>${c.n}</td><td><b>${money(c.total)}</b></td></tr>`).join("")||`<tr><td colspan="5" class="muted">Nenhum cliente encontrado.</td></tr>`}
function renderReports(){const ok=state.orders.filter(o=>statusOf(o.observacoes)!=="cancelado"),sales=ok.reduce((a,o)=>a+Number(o.total||0),0),avg=ok.length?sales/ok.length:0; $("reportCards").innerHTML=[["Faturamento",money(sales)],["Pedidos",ok.length],["Ticket médio",money(avg)],["Clientes",state.clients.length]].map(x=>`<div class="report-card"><small>${x[0]}</small><b>${x[1]}</b></div>`).join("");const pays={};state.orders.forEach(o=>{const m=String(o.observacoes||"").match(/\[ML_PAGAMENTO\]([\s\S]*?)\[\/ML_PAGAMENTO\]/);const p=m?m[1]:"Não informado";pays[p]=(pays[p]||0)+1});$("paymentReport").innerHTML=Object.entries(pays).map(x=>`<div class="list-row"><span>${esc(x[0])}</span><strong>${x[1]}</strong></div>`).join("")||`<p class="muted">Sem dados.</p>`;const counts={};state.orders.flatMap(o=>itemsOf(o.observacoes)).forEach(i=>counts[i.nome]=(counts[i.nome]||0)+Number(i.quantidade||1));$("reportProducts").innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>`<div class="list-row"><span>${esc(x[0])}</span><strong>${x[1]}</strong></div>`).join("")||`<p class="muted">Sem vendas.</p>`}
async function loadSettings(){const x=await cfgGet("loja_config",{});$("storeName").value=x.nome||"Miguel Lanches";$("storePhone").value=x.telefone||"";$("storeHours").value=x.horario||"";$("minOrder").value=x.minimo??45;$("deliveryFee").value=x.taxaEntrega??0;$("deliveryEnabled").checked=x.entrega!==false;$("pickupEnabled").checked=x.retirada!==false;const pr=await cfgGet("impressao_config",{});$("printStore").value=pr.nome||"MIGUEL LANCHES";$("printWidth").value=String(pr.largura||58)}
function closeModal(){$("modal").classList.add("hidden")}
function nav(page){state.page=page;document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.page===page));document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id==="page-"+page));const names={dashboard:["Dashboard","Visão geral da operação"],pedidos:["Pedidos","Gestão em tempo real"],cardapio:["Cardápio","Produtos conectados ao cliente"],categorias:["Categorias","Organização do cardápio"],opcoes:["Opções / adicionais","Configurações compartilhadas"],clientes:["Clientes","Histórico dos consumidores"],promocoes:["Promoções","Campanhas do cardápio"],relatorios:["Relatórios","Indicadores de vendas"],impressoras:["Impressoras","Impressão térmica"],config:["Configurações","Loja e entrega"]};$("pageTitle").textContent=names[page][0];$("pageSubtitle").textContent=names[page][1]}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>nav(b.dataset.page));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>nav(b.dataset.go));
document.querySelectorAll("#orderTabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#orderTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.filter;renderOrders()});
$("refreshBtn").onclick=load;$("productSearch").oninput=renderProducts;$("productCat").onchange=renderProducts;$("clientSearch").oninput=renderClients;$("newProductBtn").onclick=()=>productForm();$("newCatBtn").onclick=()=>categoryForm();$("newOptionBtn").onclick=optionForm;$("newPromoBtn").onclick=promoForm;$("closeModal").onclick=closeModal;
$("saveStore").onclick=async()=>{await cfgSave("loja_config",{nome:$("storeName").value,telefone:$("storePhone").value,horario:$("storeHours").value,minimo:Number($("minOrder").value||0),taxaEntrega:Number($("deliveryFee").value||0),entrega:$("deliveryEnabled").checked,retirada:$("pickupEnabled").checked});toast("Configurações salvas")};
$("saveDelivery").onclick=async()=>{const x=await cfgGet("loja_config",{});Object.assign(x,{taxaEntrega:Number($("deliveryFee").value||0),entrega:$("deliveryEnabled").checked,retirada:$("pickupEnabled").checked});await cfgSave("loja_config",x);toast("Entrega salva")};
$("savePrint").onclick=async()=>{await cfgSave("impressao_config",{nome:$("printStore").value,largura:Number($("printWidth").value)});toast("Preferência salva")};
$("testPrint").onclick=()=>{const w=open("","_blank","width=420,height=600");if(!w)return;w.document.write(`<html><head><style>@page{size:${$("printWidth").value}mm auto;margin:0}body{width:${$("printWidth").value}mm;font:12px Arial;padding:3mm;box-sizing:border-box}.c{text-align:center}.l{border-top:1px dashed #000;margin:10px 0}</style></head><body><div class=c><b>${esc($("printStore").value)}</b><br>TESTE DE IMPRESSÃO<br>${new Date().toLocaleString("pt-BR")}</div><div class=l></div>Impressão térmica ${$("printWidth").value} mm<div class=l></div><div class=c>OK</div><script>window.print()</script></body></html>`);w.document.close()};
$("soundBtn").onclick=()=>{state.sound=!state.sound;$("soundBtn").textContent="Som: "+(state.sound?"ligado":"desligado")};
$("exportCsv").onclick=()=>{const rows=[["pedido","cliente","telefone","total","status","data"],...state.orders.map(o=>[o.id,o.Cliente||"",o.telefone||"",o.total||0,statusOf(o.observacoes),o.created_at||""])];const csv=rows.map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="miguel-lanches-pedidos.csv";a.click()};
db.channel("miguel-admin-realtime").on("postgres_changes",{event:"*",schema:"public",table:"pedidos"},async(payload)=>{const wasNew=payload.eventType==="INSERT";await load();if(wasNew&&state.sound){try{new Audio("data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YQAAAAA=").play()}catch{}}}).subscribe();
load();
