const CFG=window.ML_CONFIG||{};
const db=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_KEY);
const $=id=>document.getElementById(id);
const money=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const norm=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const state={orders:[],products:[],cats:[],clients:[],filter:"todos",options:[],promos:[],page:"dashboard",sound:true,ready:false};
const statusOf=v=>{const m=[...String(v||"").matchAll(/\[ML_STATUS\](novo|preparo|entrega|entregue|cancelado)\[\/ML_STATUS\]/g)];return m.length?m.at(-1)[1]:"novo"};
const itemsOf=v=>{const m=String(v||"").match(/\[ML_ITENS\]([\s\S]*?)\[\/ML_ITENS\]/);if(!m)return[];try{return JSON.parse(decodeURIComponent(m[1]))}catch{return[]}};
const cleanMeta=v=>String(v||"").replace(/\n?\[ML_[A-Z_]+\][\s\S]*?\[\/ML_[A-Z_]+\]/g,"").trim();
const setStatus=(v,s)=>String(v||"").replace(/\n?\[ML_STATUS\][\s\S]*?\[\/ML_STATUS\]/g,"").trim()+`\n[ML_STATUS]${s}[/ML_STATUS]`;
const label=s=>({novo:"Pedido novo",preparo:"Preparando",entrega:"Saiu para entrega",entregue:"Entregue",cancelado:"Cancelado"}[s]||s);

function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2300)}
async function cfgGet(key,fallback={}){const r=await db.from("configuracoes").select("valor").eq("chave",key).maybeSingle();if(r.error||!r.data)return fallback;try{return JSON.parse(r.data.valor||"null")??fallback}catch{return fallback}}
async function cfgSave(key,val){const r=await db.from("configuracoes").upsert({chave:key,valor:JSON.stringify(val),updated_at:new Date().toISOString()},{onConflict:"chave"});if(r.error)throw r.error}
function go(page){state.page=page;document.querySelectorAll(".nav").forEach(b=>b.classList.toggle("active",b.dataset.page===page));document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id==="page-"+page));const n={dashboard:["Dashboard","Visão geral da operação"],pedidos:["Pedidos","Pedidos novos e andamento da operação"],cardapio:["Cardápio","Produtos conectados ao cliente"],categorias:["Categorias","Organização do cardápio"],opcoes:["Opções / adicionais","Configurações compartilhadas"],clientes:["Clientes","Histórico dos clientes"],promocoes:["Promoções","Campanhas do cardápio"],relatorios:["Relatórios","Indicadores de vendas"],impressoras:["Impressoras","Impressão térmica"],config:["Configurações","Loja e entrega"]}[page]||["Admin",""];$("pageTitle").textContent=n[0];$("pageSubtitle").textContent=n[1];closeMobile()}
function closeMobile(){$("sidebar").classList.remove("mobile-open");$("mobileBackdrop").classList.remove("open")}
function setupMenu(){$("mobileMenuBtn").onclick=()=>{$("sidebar").classList.toggle("mobile-open");$("mobileBackdrop").classList.toggle("open")};$("mobileBackdrop").onclick=closeMobile;document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>go(b.dataset.page))}
function setupCommon(){$("refreshBtn").onclick=loadAll;document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll("#orderTabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#orderTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.filter;renderOrders()});$("productSearch").oninput=renderProducts;$("productCat").onchange=renderProducts;$("clientSearch").oninput=renderClients;$("newProductBtn").onclick=()=>productForm();$("newCatBtn").onclick=()=>categoryForm();$("newOptionBtn").onclick=optionForm;$("newPromoBtn").onclick=promoForm;$("closeModal").onclick=closeModal;$("soundBtn").onclick=()=>{state.sound=!state.sound;$("soundBtn").textContent="Som: "+(state.sound?"ligado":"desligado")};$("saveStore").onclick=saveStore;$("saveDelivery").onclick=saveDelivery;$("savePrint").onclick=savePrint;$("testPrint").onclick=testPrint;$("exportCsv").onclick=exportCsv}

async function isAdmin(){const s=await db.auth.getSession();if(!s.data.session)return false;const r=await db.rpc("is_admin");return !r.error&&r.data===true}
async function waitAuth(){let tries=0;while(tries<120){if(await isAdmin())return true;await new Promise(r=>setTimeout(r,500));tries++}return false}

async function loadAll(){
 if(!state.ready)return;
 const [o,p,c,cl]=await Promise.all([
  db.from("pedidos").select("*").order("created_at",{ascending:false}).limit(500),
  db.from("produtos").select("*,categorias(nome,emoji,imagem_url)").order("ordem"),
  db.from("categorias").select("*").order("ordem"),
  db.from("clientes").select("*").order("nome")
 ]);
 state.orders=o.data||[];state.products=p.data||[];state.cats=c.data||[];state.clients=cl.data||[];
 $("connection").textContent=(o.error||p.error||c.error||cl.error)?"Conectado com avisos":"Conectado";
 if(o.error)toast("Pedidos: "+o.error.message);
 renderAll();
}
function renderAll(){renderDashboard();renderOrders();renderProducts();renderCats();renderClients();renderReports();renderOptions();renderPromos();loadSettings()}
function renderDashboard(){
 const valid=state.orders.filter(o=>statusOf(o.observacoes)!=="cancelado"),today=new Date().toISOString().slice(0,10),todayOrders=valid.filter(o=>(o.created_at||"").slice(0,10)===today),sales=todayOrders.reduce((a,o)=>a+Number(o.total||0),0);
 $("kpis").innerHTML=[["Pedidos hoje",todayOrders.length],["Faturamento hoje",money(sales)],["Preparando",state.orders.filter(o=>statusOf(o.observacoes)==="preparo").length],["Novos",state.orders.filter(o=>statusOf(o.observacoes)==="novo").length]].map(x=>`<div class=kpi><small>${x[0]}</small><b>${x[1]}</b></div>`).join("");
 const days=[...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const k=d.toISOString().slice(0,10);return{label:d.toLocaleDateString("pt-BR",{weekday:"short"}).replace(".",""),value:valid.filter(o=>(o.created_at||"").slice(0,10)===k).reduce((a,o)=>a+Number(o.total||0),0)}}),max=Math.max(...days.map(x=>x.value),1);
 $("salesChart").innerHTML=days.map(x=>`<div class=bar style="height:${Math.max(5,x.value/max*175)}px"><b>${money(x.value).replace(",00","")}</b><span>${x.label}</span></div>`).join("");
 const sts=["novo","preparo","entrega","entregue","cancelado"],tot=Math.max(state.orders.length,1);
 $("statusChart").innerHTML=sts.map(s=>`<div class=status-row><span>${label(s)}</span><div class=status-track><div class="status-fill ${s==="novo"||s==="cancelado"?"red":s==="entregue"?"green":""}" style="width:${state.orders.filter(o=>statusOf(o.observacoes)===s).length/tot*100}%"></div></div><b>${state.orders.filter(o=>statusOf(o.observacoes)===s).length}</b></div>`).join("");
 $("recentOrders").innerHTML=state.orders.slice(0,8).map(o=>`<div class=list-row><span><b>#${String(o.id).slice(-5)}</b> · ${esc(o.Cliente||"Cliente")}<small>${new Date(o.created_at).toLocaleString("pt-BR")}</small></span><strong>${money(o.total)}</strong></div>`).join("")||'<p class=muted>Nenhum pedido.</p>';
 const counts={};state.orders.flatMap(o=>itemsOf(o.observacoes)).forEach(i=>counts[i.nome]=(counts[i.nome]||0)+Number(i.quantidade||1));$("topProducts").innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,7).map((x,i)=>`<div class=list-row><span><b>${i+1}.</b> ${esc(x[0])}</span><strong>${x[1]}</strong></div>`).join("")||'<p class=muted>Ainda sem vendas.</p>';
 $("newBadge").textContent=state.orders.filter(o=>statusOf(o.observacoes)==="novo").length;
}

function renderOrders(){
 const counts={todos:state.orders.length,novo:0,preparo:0,entrega:0,entregue:0,cancelado:0};state.orders.forEach(o=>counts[statusOf(o.observacoes)]++);
 Object.entries(counts).forEach(([k,v])=>{const e=$("count"+k[0].toUpperCase()+k.slice(1));if(e)e.textContent=v});
 const groups=[["novo","Pedido novo","new-col"],["preparo","Preparando","prep-col"],["entrega","Saiu para entrega","delivery-col"],["entregue","Entregue","done-col"]];
 $("orders").innerHTML=groups.map(([s,title,cl])=>{let a=state.orders.filter(o=>statusOf(o.observacoes)===s);if(state.filter!=="todos")a=a.filter(o=>s===state.filter);return `<section class="orders-column ${cl}"><div class=orders-column-head><h2>${title}</h2><b>${a.length}</b></div>${a.map(orderCard).join("")||'<div class=board-empty>Nenhum pedido</div>'}</section>`}).join("");
 if(state.filter==="cancelado")$("orders").innerHTML=`<section class="orders-column"><div class=orders-column-head><h2>Cancelados</h2><b>${counts.cancelado}</b></div>${state.orders.filter(o=>statusOf(o.observacoes)==="cancelado").map(orderCard).join("")||'<div class=board-empty>Nenhum pedido</div>'}</section>`;
 document.querySelectorAll("[data-print]").forEach(b=>b.onclick=()=>printOrder(state.orders.find(o=>String(o.id)===String(b.dataset.print))));
 document.querySelectorAll("[data-next]").forEach(b=>b.onclick=async()=>{if(b.dataset.next==="cancelado"&&!confirm("Cancelar este pedido?"))return;await changeStatus(b.dataset.id,b.dataset.next)});
}
function orderCard(o){
 const s=statusOf(o.observacoes),its=itemsOf(o.observacoes),obs=cleanMeta(o.observacoes);
 return `<article class="board-card ${s==="novo"?"new-card":""}"><div class=board-top><h3>Pedido #${String(o.id).slice(-5)}</h3><span class=board-time>${new Date(o.created_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</span></div><div class=board-client>${esc(o.Cliente||"Cliente")}</div><div class=board-items>${its.map(i=>`<div><b>${Number(i.quantidade||1)}x</b> ${esc(i.nome)} <span class=muted>— ${money(Number(i.preco||0)*Number(i.quantidade||1))}</span>${i.adicionais?.length?`<br><small>+ ${i.adicionais.map(a=>esc(a.nome)).join(", ")}</small>`:""}${i.obs?`<br><small>Obs: ${esc(i.obs)}</small>`:""}</div>`).join("")||"<div>Itens não detalhados</div>"}</div><div class=board-address>${esc(o.endereco||"Retirada")}${o.referencia?" · "+esc(o.referencia):""}</div>${obs?`<div class=board-address><b>Obs:</b> ${esc(obs)}</div>`:""}<div class=board-total><span>Total</span><b>${money(o.total)}</b></div><div class=board-actions><button class=btn-print data-print="${o.id}">Imprimir</button>${s==="novo"?`<button class=btn-primary data-id="${o.id}" data-next=preparo>Preparar</button><button class=btn-danger data-id="${o.id}" data-next=cancelado>Cancelar</button>`:""}${s==="preparo"?`<button class=btn-blue data-id="${o.id}" data-next=entrega>Sair para entrega</button>`:""}${s==="entrega"?`<button class=btn-green data-id="${o.id}" data-next=entregue>Entregue</button>`:""}</div></article>`
}
async function changeStatus(id,s){const o=state.orders.find(x=>String(x.id)===String(id));if(!o)return;const novo=setStatus(o.observacoes,s),r=await db.from("pedidos").update({observacoes:novo}).eq("id",o.id);if(r.error)return toast("Erro: "+r.error.message);o.observacoes=novo;renderAll();toast("Status atualizado")}
function printOrder(o){if(!o)return;const its=itemsOf(o.observacoes),obs=cleanMeta(o.observacoes),w=open("","_blank","width=420,height=700");if(!w)return toast("Permita pop-ups para imprimir");w.document.write(`<html><head><meta charset=utf-8><title>Pedido</title><style>@page{size:58mm auto;margin:0}body{width:58mm;margin:0;padding:3mm;font:12px Arial;color:#000}.c{text-align:center}.l{border-top:1px dashed #000;margin:7px 0}.r{padding:5px 0;border-bottom:1px dotted #777}.t{display:flex;justify-content:space-between;font-weight:900;font-size:15px}</style></head><body><div class=c><b style="font-size:17px">MIGUEL LANCHES</b><br>PEDIDO #${String(o.id).slice(-5)}<br>${new Date(o.created_at).toLocaleString("pt-BR")}</div><div class=l></div><b>CLIENTE:</b> ${esc(o.Cliente||"Cliente")}<br><b>TELEFONE:</b> ${esc(o.telefone||"")}<br><b>END:</b> ${esc(o.endereco||"Retirada")}<br><b>REF:</b> ${esc(o.referencia||"—")}<div class=l></div>${its.map(i=>`<div class=r><b>${Number(i.quantidade||1)}x</b> ${esc(i.nome)}<br>${money(Number(i.preco||0)*Number(i.quantidade||1))}${i.adicionais?.length?`<br><small>+ ${i.adicionais.map(a=>esc(a.nome)).join(", ")}</small>`:""}${i.obs?`<br><small>Obs: ${esc(i.obs)}</small>`:""}</div>`).join("")}<div class=l></div><b>OBS:</b> ${esc(obs||"—")}<div class=l></div><div class=t><span>TOTAL</span><span>${money(o.total)}</span></div><div class=l></div><div class=c>Obrigado!</div><script>window.print()<\/script></body></html>`);w.document.close()}

function renderProducts(){const q=norm($("productSearch").value),cat=$("productCat").value;$("productCat").innerHTML='<option value="">Todas as categorias</option>'+state.cats.map(c=>`<option value="${c.id}" ${String(c.id)===String(cat)?"selected":""}>${esc(c.nome)}</option>`).join("");const rows=state.products.filter(p=>(!q||norm(p.nome).includes(q)||norm(p.descricao).includes(q))&&(!cat||String(p.categoria_id)===String(cat)));$("productsTable").innerHTML=rows.map(p=>`<tr><td><div class=product-cell>${p.imagem_url?`<img class=product-img src="${esc(p.imagem_url)}">`:'<span class=product-img></span>'}<span><b>${esc(p.nome)}</b><small class=muted>${esc(p.descricao||"")}</small></span></div></td><td>${esc(p.categorias?.nome||"—")}</td><td><b>${money(p.preco)}</b></td><td><button class="toggle ${p.destaque?"on":""}" data-feature="${p.id}"></button></td><td><button class="toggle ${p.ativo!==false?"on":""}" data-active="${p.id}"></button></td><td><button class=ghost data-edit="${p.id}">Editar</button></td></tr>`).join("")||'<tr><td colspan=6 class=muted>Nenhum produto.</td></tr>';document.querySelectorAll("[data-feature]").forEach(b=>b.onclick=()=>toggleProduct(b.dataset.feature,"destaque",!b.classList.contains("on")));document.querySelectorAll("[data-active]").forEach(b=>b.onclick=()=>toggleProduct(b.dataset.active,"ativo",!b.classList.contains("on")));document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>productForm(state.products.find(p=>String(p.id)===String(b.dataset.edit))))}
async function toggleProduct(id,field,value){const r=await db.from("produtos").update({[field]:value}).eq("id",id);if(r.error)return toast(r.error.message);await loadAll();toast("Alterado")}
function productForm(p={}){$("modalBody").innerHTML=`<h2>${p.id?"Editar produto":"Novo produto"}</h2><div class=form-grid><label class=field>Nome<input id=fName value="${esc(p.nome||"")}"></label><label class=field>Categoria<select id=fCat>${state.cats.map(c=>`<option value="${c.id}" ${String(c.id)===String(p.categoria_id)?"selected":""}>${esc(c.nome)}</option>`).join("")}</select></label><label class=field>Preço<input id=fPrice type=number step=.01 value="${Number(p.preco||0)}"></label><label class=field>Imagem URL<input id=fImage value="${esc(p.imagem_url||"")}"></label><label class=field style="grid-column:1/-1">Descrição<textarea id=fDesc rows=3>${esc(p.descricao||"")}</textarea></label></div><button class=primary id=saveProduct>Salvar produto</button>`;$("modal").classList.remove("hidden");$("saveProduct").onclick=async()=>{const d={nome:$("fName").value.trim(),categoria_id:$("fCat").value||null,preco:Number($("fPrice").value||0),imagem_url:$("fImage").value.trim()||null,descricao:$("fDesc").value.trim(),ativo:p.ativo!==false};if(!d.nome)return toast("Informe o nome.");const r=p.id?await db.from("produtos").update(d).eq("id",p.id):await db.from("produtos").insert(d);if(r.error)return toast("Erro: "+r.error.message);closeModal();await loadAll();toast("Produto salvo")}}
function renderCats(){$("categoryGrid").innerHTML=state.cats.map(c=>`<div class=category-card>${c.imagem_url?`<img class=cat-img src="${esc(c.imagem_url)}">`:'<div class=cat-img></div>'}<div><h3>${esc(c.nome)}</h3><p>${c.ativo===false?"Inativa":"Ativa"} · ordem ${c.ordem||0}</p></div><div class=cat-actions><button class=ghost data-cat-edit="${c.id}">Editar</button></div></div>`).join("")||'<div class=panel>Nenhuma categoria.</div>';document.querySelectorAll("[data-cat-edit]").forEach(b=>b.onclick=()=>categoryForm(state.cats.find(c=>String(c.id)===String(b.dataset.catEdit))))}
function categoryForm(c={}){$("modalBody").innerHTML=`<h2>${c.id?"Editar categoria":"Nova categoria"}</h2><label class=field>Nome<input id=cName value="${esc(c.nome||"")}"></label><label class=field>Emoji<input id=cEmoji value="${esc(c.emoji||"📦")}"></label><label class=field>Imagem URL<input id=cImage value="${esc(c.imagem_url||"")}"></label><label class=field>Ordem<input id=cOrder type=number value="${Number(c.ordem||99)}"></label><label class=check><input id=cActive type=checkbox ${c.ativo!==false?"checked":""}> Ativa</label><button class=primary id=saveCat>Salvar categoria</button>`;$("modal").classList.remove("hidden");$("saveCat").onclick=async()=>{const d={nome:$("cName").value.trim(),emoji:$("cEmoji").value.trim()||"📦",imagem_url:$("cImage").value.trim()||null,ordem:Number($("cOrder").value||99),ativo:$("cActive").checked};if(!d.nome)return toast("Informe o nome.");const r=c.id?await db.from("categorias").update(d).eq("id",c.id):await db.from("categorias").insert(d);if(r.error)return toast("Erro: "+r.error.message);closeModal();await loadAll();toast("Categoria salva")}}
async function renderOptions(){state.options=await cfgGet("opcoes_catalogo",[]);$("optionsList").innerHTML=state.options.map((x,i)=>`<div class=option-row><b>${esc(x.nome)}</b><span>${esc(x.categoria||"Geral")}</span><span>${money(x.preco||0)}</span><button class=danger-btn data-del-opt="${i}">Excluir</button></div>`).join("")||'<p class=muted>Nenhuma opção cadastrada.</p>';document.querySelectorAll("[data-del-opt]").forEach(b=>b.onclick=async()=>{state.options.splice(Number(b.dataset.delOpt),1);try{await cfgSave("opcoes_catalogo",state.options);renderOptions();toast("Opção removida")}catch(e){toast("Erro: "+e.message)}})}
function optionForm(){$("modalBody").innerHTML='<h2>Nova opção</h2><label class=field>Nome<input id=oName placeholder="Ex.: Bacon"></label><label class=field>Categoria<input id=oCat placeholder="Ex.: Lanches"></label><label class=field>Preço adicional<input id=oPrice type=number step=.01 value=0></label><button class=primary id=saveOpt>Salvar</button>';$("modal").classList.remove("hidden");$("saveOpt").onclick=async()=>{const x={nome:$("oName").value.trim(),categoria:$("oCat").value.trim(),preco:Number($("oPrice").value||0)};if(!x.nome)return toast("Informe o nome.");try{state.options.push(x);await cfgSave("opcoes_catalogo",state.options);closeModal();renderOptions();toast("Opção salva")}catch(e){toast("Erro: "+e.message)}}}
async function renderPromos(){state.promos=await cfgGet("promocoes",[]);$("promoList").innerHTML=state.promos.map((x,i)=>`<div class=promo-row><b>${esc(x.nome)}</b><span>${Number(x.desconto||0)}% de desconto</span><span>${x.ativa?"Ativa":"Inativa"}</span><button class="${x.ativa?"ghost":"primary"}" data-promo="${i}">${x.ativa?"Desativar":"Ativar"}</button></div>`).join("")||'<p class=muted>Nenhuma promoção.</p>';document.querySelectorAll("[data-promo]").forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.promo);state.promos[i].ativa=!state.promos[i].ativa;try{await cfgSave("promocoes",state.promos);renderPromos()}catch(e){toast("Erro: "+e.message)}})}
function promoForm(){$("modalBody").innerHTML='<h2>Nova promoção</h2><label class=field>Nome<input id=prName placeholder="Ex.: Combo da semana"></label><label class=field>Desconto %<input id=prDiscount type=number min=0 max=100 value=10></label><button class=primary id=savePromo>Salvar</button>';$("modal").classList.remove("hidden");$("savePromo").onclick=async()=>{const x={nome:$("prName").value.trim(),desconto:Number($("prDiscount").value||0),ativa:true,criadaEm:new Date().toISOString()};if(!x.nome)return toast("Informe o nome.");try{state.promos.push(x);await cfgSave("promocoes",state.promos);closeModal();renderPromos();toast("Promoção criada")}catch(e){toast("Erro: "+e.message)}}}
function renderClients(){const q=norm($("clientSearch").value),rows=state.clients.filter(c=>!q||norm(c.nome).includes(q)||String(c.telefone||"").includes(q)).map(c=>{const o=state.orders.filter(x=>String(x.telefone||"")===String(c.telefone||""));return{...c,n:o.length,total:o.reduce((a,x)=>a+Number(x.total||0),0)}});$("clientsTable").innerHTML=rows.map(c=>`<tr><td><b>${esc(c.nome)}</b></td><td>${esc(c.telefone||"")}</td><td>${esc(c.endereco||"")}</td><td>${c.n}</td><td><b>${money(c.total)}</b></td></tr>`).join("")||'<tr><td colspan=5 class=muted>Nenhum cliente encontrado.</td></tr>'}
function renderReports(){const ok=state.orders.filter(o=>statusOf(o.observacoes)!=="cancelado"),sales=ok.reduce((a,o)=>a+Number(o.total||0),0);$("reportCards").innerHTML=[["Faturamento",money(sales)],["Pedidos",ok.length],["Ticket médio",money(ok.length?sales/ok.length:0)],["Clientes",state.clients.length]].map(x=>`<div class=report-card><small>${x[0]}</small><b>${x[1]}</b></div>`).join("");const pays={};state.orders.forEach(o=>{const m=String(o.observacoes||"").match(/\[ML_PAGAMENTO\]([\s\S]*?)\[\/ML_PAGAMENTO\]/);const p=m?m[1]:"Não informado";pays[p]=(pays[p]||0)+1});$("paymentReport").innerHTML=Object.entries(pays).map(x=>`<div class=list-row><span>${esc(x[0])}</span><strong>${x[1]}</strong></div>`).join("")||'<p class=muted>Sem dados.</p>';const c={};state.orders.flatMap(o=>itemsOf(o.observacoes)).forEach(i=>c[i.nome]=(c[i.nome]||0)+Number(i.quantidade||1));$("reportProducts").innerHTML=Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>`<div class=list-row><span>${esc(x[0])}</span><strong>${x[1]}</strong></div>`).join("")||'<p class=muted>Sem vendas.</p>'}
async function loadSettings(){const x=await cfgGet("loja_config",{});$("storeName").value=x.nome||"Miguel Lanches";$("storePhone").value=x.telefone||"";$("storeHours").value=x.horario||"";$("minOrder").value=x.minimo??45;$("deliveryFee").value=x.taxaEntrega??0;$("deliveryEnabled").checked=x.entrega!==false;$("pickupEnabled").checked=x.retirada!==false;const p=await cfgGet("impressao_config",{});$("printStore").value=p.nome||"MIGUEL LANCHES";$("printWidth").value=String(p.largura||58)}
async function saveStore(){try{await cfgSave("loja_config",{nome:$("storeName").value,telefone:$("storePhone").value,horario:$("storeHours").value,minimo:Number($("minOrder").value||0),taxaEntrega:Number($("deliveryFee").value||0),entrega:$("deliveryEnabled").checked,retirada:$("pickupEnabled").checked});toast("Configurações salvas")}catch(e){toast("Erro: "+e.message)}}
async function saveDelivery(){try{const x=await cfgGet("loja_config",{});Object.assign(x,{taxaEntrega:Number($("deliveryFee").value||0),entrega:$("deliveryEnabled").checked,retirada:$("pickupEnabled").checked});await cfgSave("loja_config",x);toast("Entrega salva")}catch(e){toast("Erro: "+e.message)}}
async function savePrint(){try{await cfgSave("impressao_config",{nome:$("printStore").value,largura:Number($("printWidth").value)});toast("Preferência salva")}catch(e){toast("Erro: "+e.message)}}
function testPrint(){const w=open("","_blank","width=420,height=600");if(!w)return toast("Permita pop-ups");const width=$("printWidth").value;w.document.write(`<html><head><style>@page{size:${width}mm auto;margin:0}body{width:${width}mm;font:12px Arial;padding:3mm}.c{text-align:center}.l{border-top:1px dashed #000;margin:10px 0}</style></head><body><div class=c><b>${esc($("printStore").value)}</b><br>TESTE DE IMPRESSÃO<br>${new Date().toLocaleString("pt-BR")}</div><div class=l></div>Impressão térmica ${width} mm<div class=l></div><div class=c>OK</div><script>window.print()<\/script></body></html>`);w.document.close()}
function exportCsv(){const rows=[["pedido","cliente","telefone","total","status","data"],...state.orders.map(o=>[o.id,o.Cliente||"",o.telefone||"",o.total||0,statusOf(o.observacoes),o.created_at||""])];const csv=rows.map(r=>r.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download="miguel-lanches-pedidos.csv";a.click()}
function closeModal(){$("modal").classList.add("hidden")}

async function boot(){
 setupMenu();setupCommon();
 const ok=await waitAuth();
 if(!ok){$("connection").textContent="Aguardando administrador";return}
 state.ready=true;$("connection").textContent="Conectado";await loadAll();
 db.channel("admin-orders-live").on("postgres_changes",{event:"*",schema:"public",table:"pedidos"},async(payload)=>{const isNew=payload.eventType==="INSERT";await loadAll();if(isNew&&state.sound){try{new Audio("data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAIA+AAACABAAZGF0YQAAAAA=").play()}catch{}}}).subscribe();
 db.channel("admin-catalog-live").on("postgres_changes",{event:"*",schema:"public",table:"produtos"},loadAll).subscribe();
 db.channel("admin-category-live").on("postgres_changes",{event:"*",schema:"public",table:"categorias"},loadAll).subscribe();
}
document.addEventListener("DOMContentLoaded",boot);
